.\" Process with groff -man -Tascii unionfs.1
.\"
.TH UNIONFS 8 "July 2005" Linux
.SH NAME
Unionfs \- a unification file system for Linux
.SH SYNOPSIS

.P
.B uniondbg
[OPTION]
.I file
[ARGUMENTS]

.SH DESCRIPTION
.B uniondbg
runs unionfs debugging ioctls.  You should rarely, if ever, need to use it.
Unless you are a Unionfs developer, the only option that is useful is "-d"

.SH OPTIONS
.IP "-d"
sets or gets the debugging value.  If no additional arguments are specified,
then the current debugging level is printed.  If an additional argument is
given, the debugging value is set to that argument.

.IP "-c"
causes the kernel to print out the branch reference counts.
.IP "-g"
increments the superblock generation number.
.IP "-s"
duplicates the super-block.


.SH AUTHORS
Charles Wright <cwright@cs.sunysb.edu>,
Mohammad Zubair <mzubair@ic.sunysb.edu>,
Erez Zadok <ezk@cs.sunysb.edu>
.SH "SEE ALSO"
.BR unionfs(4),
.BR unionctl(8),
http://www.fsl.cs.sunysb.edu/

\"  LocalWords:  groff Tascii unionfs uniondbg ioctls superblock Zubair Erez
\"  LocalWords:  unionctl
