# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 * For more information, see http://www.mozilla.org/unix/customizing.html#prefs
 */

user_pref("app.update.enabled", false);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1149165740);
user_pref("app.update.lastUpdateTime.background-update-timer", 1149165729);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1161518625);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1161518626);
user_pref("browser.download.manager.closeWhenDone", true);
user_pref("browser.download.manager.retention", 0);
user_pref("browser.history_expire_days", 0);
user_pref("browser.history_expire_days.mirror", 9);
user_pref("browser.preferences.advanced.selectedTabIndex", 0);
user_pref("browser.preferences.privacy.selectedTabIndex", 0);
user_pref("browser.search.selectedEngine", "Google");
user_pref("browser.search.update", false);
user_pref("browser.startup.homepage", "http://www.google.com/firefox");
user_pref("browser.startup.homepage_override.mstone", "rv:1.8.1");
user_pref("extensions.disabledObsolete", true);
user_pref("extensions.dta.tool.compactmenu", true);
user_pref("extensions.dta.tool.menu", "1,1,1");
user_pref("extensions.lastAppVersion", "2.0");
user_pref("extensions.update.enabled", false);
user_pref("extensions.update.notifyUser", false);
user_pref("flashgot.defaultDM", "cURL");
user_pref("flashgot.detect.cache", "cURL");
user_pref("intl.charsetmenu.browser.cache", "ISO-8859-1, UTF-8");
user_pref("jsview.disableContext", false);
user_pref("jsview.disableStatus", false);
user_pref("jsview.openExternal", false);
user_pref("jsview.openInTabBlur", false);
user_pref("jsview.openInTabFocus", false);
user_pref("jsview.temploc", "/home/user/.mozilla/firefox/zp1qj4dn.default/temp");
user_pref("network.cookie.lifetimePolicy", 2);
user_pref("network.cookie.prefsMigrated", true);
user_pref("pref.privacy.disable_button.view_passwords", false);
user_pref("privacy.item.cookies", true);
user_pref("privacy.sanitize.didShutdownSanitize", true);
user_pref("privacy.sanitize.promptOnSanitize", false);
user_pref("privacy.sanitize.sanitizeOnShutdown", true);
user_pref("security.warn_entering_secure", false);
user_pref("signon.rememberSignons", false);
user_pref("urlclassifier.keyupdatetime.https://sb-ssl.google.com/safebrowsing/getkey?client=navclient-auto-ffox2.0&", 1161605028);
user_pref("urlclassifier.tableversion.goog-black-enchash", "1.12220");
user_pref("urlclassifier.tableversion.goog-black-url", "1.6827");
user_pref("urlclassifier.tableversion.goog-white-domain", "1.17");
user_pref("urlclassifier.tableversion.goog-white-url", "1.371");
user_pref("webdeveloper.custom.1.color", "#ff0000");
user_pref("webdeveloper.custom.2.color", "#33ff33");
user_pref("webdeveloper.custom.3.color", "#3333ff");
user_pref("webdeveloper.custom.4.color", "#ff0000");
user_pref("webdeveloper.custom.5.color", "#33ff33");
user_pref("webdeveloper.disable.styles.key", "S");
user_pref("webdeveloper.display.element.information.key", "F");
user_pref("webdeveloper.edit.color.background", "#ffffff");
user_pref("webdeveloper.edit.color.text", "#000000");
user_pref("webdeveloper.edit.css.key", "E");
user_pref("webdeveloper.edit.font.size", 12);
user_pref("webdeveloper.edit.update.frequency", 2000);
user_pref("webdeveloper.feature.tooltip.color.background", "#ffff99");
user_pref("webdeveloper.feature.tooltip.color.border", "#ffcc66");
user_pref("webdeveloper.feature.tooltip.color.text", "#000000");
user_pref("webdeveloper.feature.tooltip.opacity", "0.9");
user_pref("webdeveloper.generated.content.font.size", 12);
user_pref("webdeveloper.information.tidy", true);
user_pref("webdeveloper.java.console.key", "O");
user_pref("webdeveloper.javascript.console.key", "J");
user_pref("webdeveloper.line.guides.color", "#000000");
user_pref("webdeveloper.open.tabs", true);
user_pref("webdeveloper.populate.form.fields.email", "example@example.com");
user_pref("webdeveloper.resize.1.description", "800x600");
user_pref("webdeveloper.resize.1.height", 600);
user_pref("webdeveloper.resize.1.width", 800);
user_pref("webdeveloper.resize.count", 1);
user_pref("webdeveloper.tool.1.description", "Validate CSS");
user_pref("webdeveloper.tool.1.url", "http://jigsaw.w3.org/css-validator/validator?profile=css2&warning=2&uri=");
user_pref("webdeveloper.tool.2.description", "Validate Feed");
user_pref("webdeveloper.tool.2.url", "http://validator.w3.org/feed/check.cgi?url=");
user_pref("webdeveloper.tool.3.description", "Validate HTML");
user_pref("webdeveloper.tool.3.key", "H");
user_pref("webdeveloper.tool.3.url", "http://validator.w3.org/check?verbose=1&uri=");
user_pref("webdeveloper.tool.4.description", "Validate Links");
user_pref("webdeveloper.tool.4.url", "http://validator.w3.org/checklink?check=Check&hide_type=all&summary=on&uri=");
user_pref("webdeveloper.tool.5.description", "Validate Section 508");
user_pref("webdeveloper.tool.5.url", "http://www.contentquality.com/mynewtester/cynthia.exe?rptmode=-1&url1=");
user_pref("webdeveloper.tool.6.description", "Validate WAI");
user_pref("webdeveloper.tool.6.url", "http://www.contentquality.com/mynewtester/cynthia.exe?rptmode=2&url1=");
user_pref("webdeveloper.tool.7.separator", true);
user_pref("webdeveloper.tool.8.description", "View Speed Report");
user_pref("webdeveloper.tool.8.url", "http://www.websiteoptimization.com/cgi-bin/wso/wso.pl?url=");
user_pref("webdeveloper.tool.count", 8);
user_pref("webdeveloper.toolbar.key", "T");
user_pref("webdeveloper.validate.local.css.profile", "css2");
user_pref("webdeveloper.validate.local.html.key", "A");
user_pref("webdeveloper.version", "1.02");
user_pref("webdeveloper.view.css.key", "C");
user_pref("webdeveloper.view.source.key", "U");
user_pref("webdeveloper.view.style.information.key", "Y");
user_pref("webdeveloper.zoom.in.key", "Z");
user_pref("webdeveloper.zoom.out.key", "X");
user_pref("xpinstall.whitelist.add", "");
user_pref("xpinstall.whitelist.add.103", "");
